### ISSUE TITLE
InjectionExtension does not work on Oxygen / Junit <5.4

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1524]
InjectionExtension does not work on Oxygen / Junit <5.4

https://github.com/itemis/xtext-reference-projects/issues/126

```
java.lang.NoSuchMethodError: org.junit.jupiter.api.extension.ExtensionContext.getRequiredTestInstances()Lorg/junit/jupiter/api/extension/TestInstances;
at org.eclipse.xtext.testing.extensions.InjectionExtension.beforeEach(InjectionExtension.java:62)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$null$0(TestMethodTestDescriptor.java:126)
```

**Comment by cdietrich** [comment]
Fixed in 2.23
